apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker-prod
  namespace: argocd
  labels:
    env: prod
    app: worker
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ShivSingh96/gitops-multienv-bootstrap
    targetRevision: HEAD
    path: charts/worker
    helm:
      valueFiles:
      - values.yaml
      - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
