apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worker.name" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "worker.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: WORKER_CONCURRENCY
          value: {{ .Values.queue.concurrency | quote }}
        - name: WORKER_QUEUES
          value: {{ .Values.queue.queues | quote }}
        {{- range $key, $val := .Values.env }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
